export const STATUS_CODE = {
  OK: 200,
  TRIPLEA: 151,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  INFO: 250,
  NON_AUTHORITATIVE: 203,
  BAD_REQUEST: 400,
  UN_AUTHORIZED: 401,
  FORBIDDEN: 403,
  RESOURCE_NOT_FOUND: 404,
  PROXY_AUTH_FAILED: 412,
  TOO_MANY_REQUESTS: 429,
  VALIDATION_FAILURE: 450,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  SERVER_TIMEOUT: 504,
} as const;

export const ERROR_MSGS = {
  INTERNAL_SERVER_ERROR: 'Unable to process,Please Try Again',
  UPDATED_FAILED: 'Updated Failed',
  INVALID_USER_TYPE:'invalid userType',
  ACCOUNT_EXISTS: 'Account already exists. Please login',
  EMAIL_EXISTS: 'Email already exists.',
  ACCOUNT_NOT_FOUND: 'Account not found, invalid Email',
  IP_LOCKED: 'Please try again later.',
  INVALID_LOGIN: 'Invalid email or/and password.',
  USER_NOT_FOUND: 'User not found',
  LOGIN_WITH_EMAIL: 'Please login with Email and password',
  INCORRECT_PASSWORD: 'current Password Incorrect',
  FORGOT_PASSWORD_TOKEN_EXPIRED: 'Token has expired.',
  BAD_AUTH: 'bad authorization!',
  TOKEN_MISSING: 'Token not provided!',
  BAD_TOKEN: 'bad token!',
} as const;

export const INFO_MSGS = {
  NO_DATA: 'No data found',
  CREATED_SUCCESSFULLY: 'Created successfully',
  UPDATED_SUCCESSFULLY: 'Updated successfully',
  SUCCESS: 'Request Success',
  SUCCESSFUL_REGISTER: 'Your registration is successful.',
  SUCCESSFUL_UPDATE: 'Successfully updated',
  SUCCESSFUL_LOGIN: 'Successfully Logged In.',
  PASSWORD_CHANGED: 'Your password has been changed successfully.',
  VERIFICATION_EMAIL: 'Verification Email send successfully.',
  EMAIL_NOT_VERIFIED: 'Email not verified, Please verify it.',
  EMAIL_VERIFIED: 'Email already Verified. Please login',
  EMAIL_SEND: 'Email sent to the registered account.',
  ACCOUNT_VERIFIED: 'Your account has been verified, Please login.',
  SUCCESSFUL_LOGOUT: 'Successfully logged out.',
  USERNAME_AVAILABLE: 'Username available',
  USERNAME_NOT_AVAILABLE: 'Username not available',
  MSG_REQUIRED: 'is required',
} as const;
